### ISSUE TITLE
TODO: README.md

### ISSUE THREAD

**Issue by Akshayanti** [Akshayanti/cross-lingual-tagging-and-parsing#1]
- [x] Explain the nomenclature of models, with the binary ending
- [x] Details of Files Included, and their organisation in the directory
- [x] Include Results and Interpretetion of them

**Comment by Akshayanti** [comment]
Done

Details of Files Included, and their organisation in the directory
